import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="th">
      {/* ใส่ bg-[#0d0f17] ที่ body จะทำให้สีดำเนียนเต็มจอ 100% ทั้งหน้าจอ */}
      <body className="bg-[#0d0f17] text-slate-100 min-h-screen antialiased">
        {children}
      </body>
    </html>
  );
}
